import assert from 'node:assert/strict'
import { test } from 'node:test'
import { derive, extractUserText, parseLines, contextTokensOf } from './transcript.ts'

type Rec = Record<string, unknown>

const userMsg = (text: string, extra: Rec = {}): Rec => ({
  type: 'user',
  cwd: '/home/user/nyan-remote',
  gitBranch: 'main',
  version: '2.1.226',
  timestamp: '2026-08-11T09:00:00.000Z',
  message: { role: 'user', content: text },
  ...extra,
})

test('parseLines: drops broken lines and the cut-off ends of a partial read', () => {
  const text = ['{"type":"a"}', 'これはJSONではない', '{"type":"b"}', '{"type":"c'].join('\n')
  assert.deepEqual(parseLines(text).map((r) => r['type']), ['a', 'b'])

  // When reading started mid-file, drop the first line
  assert.deepEqual(parseLines('{"broken":1}\n{"type":"b"}', true).map((r) => r['type']), ['b'])
  // When reading stopped mid-file, drop the last line
  assert.deepEqual(parseLines('{"type":"a"}\n{"type":"b"}', false, true).map((r) => r['type']), ['a'])
})

test('derive: custom-title takes priority over ai-title', () => {
  const d = derive({
    sessionId: 'abc12345-0000',
    headRecords: [userMsg('最初の発言')],
    tailRecords: [
      { type: 'ai-title', aiTitle: 'AIが付けた要約' },
      { type: 'custom-title', customTitle: 'tmux' },
    ],
  })
  assert.equal(d.title, 'tmux')
  assert.equal(d.titleSource, 'custom')
})

test('derive: without custom, ai-title is used', () => {
  const d = derive({
    sessionId: 'abc12345-0000',
    headRecords: [userMsg('最初の発言')],
    tailRecords: [{ type: 'ai-title', aiTitle: 'Cloudflareの動作確認' }],
  })
  assert.equal(d.title, 'Cloudflareの動作確認')
  assert.equal(d.titleSource, 'ai')
})

test('derive: with several records of the same type, the last (= latest) wins', () => {
  const d = derive({
    sessionId: 's',
    headRecords: [],
    tailRecords: [
      { type: 'custom-title', customTitle: '古い名前' },
      { type: 'custom-title', customTitle: '新しい名前' },
    ],
  })
  assert.equal(d.title, '新しい名前')
})

test('derive: without a title, the first user message is used', () => {
  const d = derive({
    sessionId: 's',
    headRecords: [userMsg('別なアカウントでこのリポで数日前にやりとりしてた')],
    tailRecords: [],
  })
  assert.equal(d.titleSource, 'prompt')
  assert.equal(d.title, '別なアカウントでこのリポで数日前にやりとりしてた')
})

test('derive: if no message is usable, fall back to the basename of cwd', () => {
  const d = derive({
    sessionId: 'abc12345-9999',
    headRecords: [
      userMsg('<command-name>/compact</command-name>'),
      userMsg('Caveat: The messages below were generated by the user'),
      userMsg('これは <system-reminder> を含む'),
      userMsg('This session is being continued from a previous conversation'),
    ],
    tailRecords: [],
  })
  assert.equal(d.titleSource, 'fallback')
  assert.equal(d.title, 'nyan-remote')
})

test('derive: without cwd either, the first 8 characters of sessionId', () => {
  const d = derive({ sessionId: 'abc12345-9999', headRecords: [], tailRecords: [] })
  assert.equal(d.title, 'abc12345')
})

test('derive: long titles are truncated', () => {
  const long = 'あ'.repeat(200)
  const d = derive({
    sessionId: 's',
    headRecords: [],
    tailRecords: [{ type: 'custom-title', customTitle: long }],
  })
  assert.ok(d.title.length <= 70)
  assert.ok(d.title.endsWith('…'))
})

test('derive: picks up cwd / gitBranch / version / permissionMode / lastActivity', () => {
  const d = derive({
    sessionId: 's',
    headRecords: [userMsg('やあ')],
    tailRecords: [
      { type: 'permission-mode', permissionMode: 'auto' },
      { type: 'permission-mode', permissionMode: 'plan' },
      { type: 'assistant', timestamp: '2026-08-11T10:00:00.000Z' },
    ],
  })
  assert.equal(d.cwd, '/home/user/nyan-remote')
  assert.equal(d.gitBranch, 'main')
  assert.equal(d.cliVersion, '2.1.226')
  assert.equal(d.permissionMode, 'plan')
  assert.equal(d.lastActivity, '2026-08-11T10:00:00.000Z')
})

// ★★ Regression guard for the bug where "done" / "awaiting approval" vanished after 3 minutes (actually shipped on 2026-08-11).
//
//   Record order in the measured file:
//     12:40:00  assistant                                  ← end of the conversation
//     12:40:29  Stop hook (recorded in hookState)
//     12:40:30  system/stop_hook_summary, turn_duration     ← 0.5s later
//     12:43:36  system/away_summary                         ← ★3 minutes later
//
//   If lastActivity includes system records, once the summary is written it is judged that "there was
//   activity newer than the hook", and the list's status label disappears. **Excluding them is the requirement.**
//
// ⚠️ This used to be "tested" in status.test.ts, but the input it passed was identical to another test
//    and never went through a single line of the transcript side (= a false green). Replaced on 2026-08-13.

test('★★ derive: lastActivity is taken only from conversation records (system cleanup is not counted)', () => {
  const d = derive({
    sessionId: 's',
    headRecords: [userMsg('やあ')],
    tailRecords: [
      { type: 'assistant', timestamp: '2026-08-11T12:40:00.000Z' },
      // ↓ From here down is system cleanup. Must not be mixed into lastActivity
      { type: 'system', subtype: 'stop_hook_summary', content: 'x', timestamp: '2026-08-11T12:40:30.000Z' },
      { type: 'system', subtype: 'turn_duration', content: '12s', timestamp: '2026-08-11T12:40:30.500Z' },
      {
        type: 'system',
        subtype: 'away_summary',
        content: '離席中にテストが2件失敗しました',
        timestamp: '2026-08-11T12:43:36.000Z',
      },
    ],
  })
  // ★ Must be the time of the end of the conversation, not the away_summary 3 minutes later
  assert.equal(d.lastActivity, '2026-08-11T12:40:00.000Z')
  // ...while the summary itself is still picked up (fixing only one side is pointless)
  assert.equal(d.awaySummary, '離席中にテストが2件失敗しました')
})

test('derive: away_summary takes the last one and truncates it if long', () => {
  const d = derive({
    sessionId: 's',
    headRecords: [],
    tailRecords: [
      { type: 'system', subtype: 'away_summary', content: '古い要約' },
      { type: 'system', subtype: 'away_summary', content: 'あ'.repeat(300) },
    ],
  })
  assert.ok(d.awaySummary && d.awaySummary.length <= 161, `not truncated: ${d.awaySummary?.length}`)
  assert.ok(d.awaySummary?.startsWith('あ'))
})

test('derive: without away_summary it is undefined (an empty string is not a display element)', () => {
  const d = derive({
    sessionId: 's',
    headRecords: [userMsg('やあ')],
    tailRecords: [{ type: 'system', subtype: 'away_summary', content: '' }],
  })
  assert.equal(d.awaySummary, undefined)
})

test('★ derive: attachment also counts as activity (not only user/assistant)', () => {
  const d = derive({
    sessionId: 's',
    headRecords: [userMsg('やあ')],
    tailRecords: [
      { type: 'assistant', timestamp: '2026-08-11T12:40:00.000Z' },
      { type: 'attachment', timestamp: '2026-08-11T12:41:00.000Z' },
    ],
  })
  assert.equal(d.lastActivity, '2026-08-11T12:41:00.000Z')
})

test('extractUserText: works when content is an array / sidechain is ignored', () => {
  assert.equal(
    extractUserText({
      type: 'user',
      message: {
        content: [
          { type: 'text', text: 'ひとつめ' },
          { type: 'tool_result', content: '無視される' },
        ],
      },
    }),
    'ひとつめ',
  )
  assert.equal(extractUserText({ type: 'user', isSidechain: true, message: { content: 'x' } }), undefined)
  assert.equal(extractUserText({ type: 'assistant', message: { content: 'x' } }), undefined)
})

// ★★ How much context is currently in use (2026-08-19. Added at another session's request)
//
// ⚠️ The shape is **taken from a real transcript** (`message.usage`).
//    `input_tokens` excludes cached tokens, so in real data it was 2. The point is to add all three.

const usageRec = (u: Record<string, unknown>, type = 'assistant'): Record<string, unknown> => ({
  type,
  message: { model: 'claude-opus-5', usage: u },
})

test('★★ adds the three usage counts (dropping cached tokens changes the order of magnitude)', () => {
  // Use real values as-is
  const r = usageRec({
    input_tokens: 2,
    cache_creation_input_tokens: 1765,
    cache_read_input_tokens: 672198,
    output_tokens: 747,
  })
  assert.equal(contextTokensOf([r]), 673965)
  // ⚠️ Looking only at input_tokens gives 2 (that was the actual value)
  assert.notEqual(contextTokensOf([r]), 2)
})

test('★★ uses the last assistant (being one turn behind while responding is by design)', () => {
  const recs = [
    usageRec({ input_tokens: 10, cache_read_input_tokens: 100 }),
    { type: 'user', message: { content: 'x' } },
    usageRec({ input_tokens: 20, cache_read_input_tokens: 500 }),
    { type: 'user', message: { content: 'y' } },
  ]
  assert.equal(contextTokensOf(recs), 520)
})

test('★★ undefined when unknown (not 0 / no fail-open)', () => {
  assert.equal(contextTokensOf([]), undefined, 'empty')
  assert.equal(contextTokensOf([{ type: 'user', message: { content: 'x' } }]), undefined, 'no assistant')
  assert.equal(contextTokensOf([usageRec({})]), undefined, 'usage is empty')
  assert.equal(contextTokensOf([{ type: 'assistant', message: {} }]), undefined, 'no usage')
  assert.equal(contextTokensOf([usageRec({ input_tokens: 'x', cache_read_input_tokens: null })]), undefined, 'not a number')
  // ★ Skip broken ones and pick the usable value before them
  assert.equal(
    contextTokensOf([usageRec({ input_tokens: 5, cache_read_input_tokens: 95 }), usageRec({})]),
    100,
  )
})

test('★★ does not look past the compact boundary (it was a 15x lie on real data)', () => {
  // ⚠️ Real data (our own transcript): right after compaction the tail had only the "pre-compaction assistant",
  //    and it returned 901,602 (true value: 60,428 from the next response)
  const before = usageRec({ input_tokens: 2, cache_read_input_tokens: 901600 })
  const boundary = {
    type: 'system',
    subtype: 'compact_boundary',
    compactMetadata: { preTokens: 902839, postTokens: 14534 },
  }
  assert.equal(contextTokensOf([before, boundary]), undefined, 'returns the pre-compaction value')
  // ⚠️ Must not show postTokens (14,534) instead either (a different metric)
  assert.notEqual(contextTokensOf([before, boundary]), 14534)
  // ★ If there is a response after compaction, pick that up
  const after = usageRec({ input_tokens: 2, cache_read_input_tokens: 60426 })
  assert.equal(contextTokensOf([before, boundary, after]), 60428)
})

test('★★ values only in `iterations` (2 cases in real data / CLI 2.1.215)', () => {
  const r = usageRec({
    input_tokens: 0,
    cache_creation_input_tokens: 0,
    cache_read_input_tokens: 0,
    iterations: [
      {
        type: 'message',
        input_tokens: 2,
        cache_creation_input_tokens: 10309,
        cache_read_input_tokens: 435320,
      },
    ],
  })
  assert.equal(contextTokensOf([r]), 445631)
  // ⚠️ Do not sum them all. The **last message** is closest to "the current input"
  const multi = usageRec({
    input_tokens: 0,
    iterations: [
      { type: 'message', input_tokens: 1, cache_read_input_tokens: 99 },
      { type: 'message', input_tokens: 2, cache_read_input_tokens: 998 },
    ],
  })
  assert.equal(contextTokensOf([multi]), 1000)
  // Only message entries are used
  const other = usageRec({ input_tokens: 0, iterations: [{ type: 'tool', input_tokens: 5 }] })
  assert.equal(contextTokensOf([other]), undefined)
})

test('★★ subagent (sidechain) usage does not pollute the main number', () => {
  // ⚠️⚠️ The earlier test passed `type: 'user'`, so it **only re-checked the type check**
  //    (2026-08-19 `/code-review`, medium #2. A "false green").
  //    **Sidechain records also have `type` `assistant`**, so pass that shape
  const sub = { ...usageRec({ input_tokens: 1, cache_read_input_tokens: 9 }), isSidechain: true }
  assert.equal(contextTokensOf([sub]), undefined, 'picks up the subagent consumption')
  // ★ Even when mixed in, the main value is picked up correctly
  const main = usageRec({ input_tokens: 2, cache_read_input_tokens: 998 })
  assert.equal(contextTokensOf([main, sub]), 1000)
  // Keep the type check too, just in case
  assert.equal(contextTokensOf([usageRec({ input_tokens: 1, cache_read_input_tokens: 9 }, 'user')]), undefined)
})
